# Generated by Django 2.0.2 on 2018-04-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(help_text='Analyzed Url', max_length=300)),
                ('Title', models.TextField(default='None')),
                ('Text', models.TextField(default='None')),
                ('Classification', models.CharField(max_length=4)),
                ('Likes', models.IntegerField(default='0')),
                ('Dislikes', models.IntegerField(default='0')),
                ('Rating', models.DecimalField(decimal_places=2, default='0', max_digits=3)),
                ('imgurl', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Like', models.BooleanField(default='False')),
                ('Dislike', models.BooleanField(default='False')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakenews.Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='users',
            field=models.ManyToManyField(through='fakenews.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('url', 'user')},
        ),
    ]
